ga4:
  measurement_id: "G-4RQD2S6BLZ"
  api_secret: "hta9FCcrRsm6AIGTmxWPaA"

simulation:
  delay_seconds:
    min: 2
    max: 8

  events:
    - page_view
    - scroll
    - click
    - login
    - generate_ai_response
    - file_upload
    - search

website:
  url: "https://malik-15.github.io/g4a/"
