name: G4A Traffic Simulator

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"

  # Allow manual execution from GitHub Actions tab
  workflow_dispatch:


jobs:

  simulate:

    runs-on: ubuntu-latest


    steps:

    # Download repository
    - name: Checkout repository
      uses: actions/checkout@v4


    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    # Install dependencies
    - name: Install requirements
      run: |
        pip install  requests beautifulsoup4 pyyaml


    # Run simulator
    - name: Generate simulated traffic
      run: |
        python parse_g4a.py
